first basic version of the extension

diff --git a/gh-cpissues b/gh-cpissues
--- a/gh-cpissues
+++ b/gh-cpissues
@@ -1,47 +1,31 @@
 #!/usr/bin/env bash
 set -e
 
-echo "Hello gh-cpissues!"
+USAGE="gh cpissues <git-repo> --label <label>"
 
-USAGE="gh cpissues <git-repo> [--label <label>]"
-
-
-
+# Parse Repo argument
 if [ -z "$1" ]
 then
  echo $USAGE
  exit 1
 fi
 
-git_repo="$1"
+TEMPLATEREPO="$1"
 shift
 
 # Initialize label variable
-label=""
-test=""
+LABEL=""
 
 # Parse remaining arguments
 while [ $# -gt 0 ]; do
  arg="$1"
  case "$arg" in
     --label)
-      # Check if label argument is provided
       if [ -n "$2" ]; then
-        label="$2"
+        LABEL="$2"
         shift
       else
-        echo "Label cannot be empty"
-        exit 1
-      fi
-      shift
-      ;;
-    --test)
-      # Check if label argument is provided
-      if [ -n "$2" ]; then
-        test="$2"
-        shift
-      else
-        echo "Test cannot be empty"
+        echo "--label cannot be empty"
         exit 1
       fi
       shift
@@ -53,33 +37,26 @@ while [ $# -gt 0 ]; do
  esac
 done
 
+# Check if label is set
+if [[ -z "$LABEL" ]]; then
+ echo $USAGE
+ exit 1
+fi
 
-printf "Argument git_repo is %s\n" "$git_repo"
-printf "option label is %s\n" "$label"
-printf "option test is %s\n" "$test"
-
-exit 0
-
+# Define temp files
 REPOROOT=$(git rev-parse --show-toplevel)
-TEMPLATEDIR=$REPOROOT/.github/template
-TEMPLATECONFIG=$TEMPLATEDIR/gitconfig
-TEMPLATELABEL=$(git config -f $TEMPLATECONFIG template.issue-label)
-TEMPLATEREPO=$(git config -f $TEMPLATECONFIG template.repo)
-TEMPLATEISSUES=$TEMPLATEDIR/issues.json 
-TMPFILE=$TEMPLATEDIR/body.tmp
-CLEANUP=
+THISCOMMIT=$(git rev-parse HEAD)
+TEMPLATEISSUES=$REPOROOT/$THISCOMMIT-issues.json 
+TMPFILE=$REPOROOT/$THISCOMMIT-body.tmp
 
-cd $REPOROOT
-echo "Hello gh-cpissues!"
+echo "Copying issues labeled \"$LABEL\" from $TEMPLATEREPO"
 
+gh issue list --search "sort:created-asc" --label $LABEL -R $TEMPLATEREPO --json 'title,body' > $TEMPLATEISSUES
 
- if [ -e $TEMPLATEISSUES ] 
- then
-    echo "Using cached issues"
- else
-   gh issue list --search "sort:created-asc" --label $TEMPLATELABEL -R $TEMPLATEREPO --json 'title,body' > $TEMPLATEISSUES
-   CLEANUP="rm $TEMPLATEISSUES"
- fi
+# Check if issues were found
+if jq -e '. | length == 0' "$TEMPLATEISSUES" > /dev/null; then
+ echo "No issues found in $TEMPLATEREPO with label \"$LABEL\""
+fi
 
 for row in $(cat $TEMPLATEISSUES | jq -r '.[] | @base64'); do
     _jq() { 
@@ -94,9 +71,11 @@ for row in $(cat $TEMPLATEISSUES | jq -r '.[] | @base64'); do
      echo $(_jq '.body') > $TMPFILE
      cmd="gh issue create --title \"$(_jq '.title')\" --body-file $TMPFILE"
      eval $cmd
+     # Clean up
      rm $TMPFILE
    fi
 
 done
 
-eval $CLEANUP
+# Clean up
+eval rm $TEMPLATEISSUES
